# Generated by Django 5.0.2 on 2024-02-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_create',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_edit',
            field=models.DateField(auto_now=True),
        ),
    ]
